#!/bin/sh /etc/rc.common

USE_PROCD=1
START=95
STOP=10

APP_DIR=/opt/lx-manager
START_SCRIPT="$APP_DIR/scripts/start-r2s.sh"

start_service() {
    procd_open_instance
    procd_set_param command /bin/sh "$START_SCRIPT"
    procd_set_param respawn 3600 5 5
    procd_set_param stdout 1
    procd_set_param stderr 1
    procd_set_param limits nofile="4096 4096"
    procd_close_instance
}

stop_service() {
    :
}
